// MOVIES
export const SEARCH_MOVIES = 'SEARCH_MOVIES';
export const SEARCH_MOVIES_ERROR = 'SEARCH_MOVIES_ERROR';
export const GET_MOVIE_TRAILER = 'GET_MOVIE_TRAILER';
export const GET_MOVIE_TRAILER_ERROR = 'GET_MOVIE_TRAILER_ERROR';

export const CREATE_SESSION = 'CREATE_SESSION';
export const CREATE_SESSION_ERROR = 'CREATE_SESSION_ERROR';
export const TOKEN = 'TOKEN';
export const TOKEN_ERROR = 'TOKEN_ERROR';

export const FETCH_FAVORITES = 'FETCH_FAVORITES';
export const FETCH_FAVORITES_ERROR = 'FETCH_FAVORITES_ERROR';
export const SET_FAVORITE = 'SET_FAVORITE';
export const SET_FAVORITE_ERROR = 'SET_FAVORITE_ERROR';

export const SET_WATCH_LIST = 'SET_WATCH_LIST';
export const SET_WATCH_LIST_ERROR = 'SET_WATCH_LIST_ERROR';
export const FETCH_WATCHLIST = 'FETCH_WATCHLIST';
export const FETCH_WATCHLIST_ERROR = 'FETCH_WATCHLIST_ERROR';