export const MOVIES = {
  moviesList: [],
  moviesListError: '',
  movieTrailer: '',
  movieTrailerError: '',
  session: '',
  sessionError: '',
  token: '',
  tokenError: '',
  isFavorite: '',
  isFavoriteError: '',
  favorites: '',
  favoritesError: '',
  watchList: '',
  watchListError: '',
  isWatchList: '',
  isWatchListError: '',
};
